############################################################################
# 原則 http://jekyllrb.com/docs/configuration/#default-configuration からの
# 差分のみ記述している。記述順序も前述に従う。

### Handling Reading
exclude:
  - 'node_modules'
  - 'Gemfile'
  - 'README.md'
  - 'vendor'
# デフォルトと同じだが「utf-8で記事を書こう」という宣言的な意味合で残した。
encoding: utf-8

### Plugins
gems:
  - jemoji
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-seo-tag

### Outputting
permalink:      pretty

### Markdown Processors
kramdown:
  input: GFM

############################################################################
# 以下はvim-jp/vimconf固有の設定項目

sass:
  # commented out while under development.
  #style: compressed
